<?php ?>
<hr />
<center><small></small>&copy; <?php echo date('Y');?> <a href="/">CanUCome</a>. All rights reserved <br /> <a href="/tos.php">Terms of Service</a> | <a href="/privacy.php">Privacy Policy</a> 
 | <a href="/contact.php">Contact us</a> </small></center>
  </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../js/bootstrap.js"></script>
  

  </body>
</html>
<?php ?>